### ISSUE TITLE
Jinja templates are not being recognised

### ISSUE THREAD

**Issue by akvadrako** [tonyfast/literacy#2]
This is a pretty neat project; thanks for sharing. I'll play around with it for a while and see how it feels. So far I did encounter one more issue. This cell:

    ```
    %reload_ext literacy
    foo = 123
    foo
    ```
    {{foo}}

results in:

```
%reload_ext literacy
foo = 123
foo
{{foo}}
Out[20]: 123
```

but the template is not being recognised.

**Comment by tonyfast** [comment]
The jinja templates are not by default.  There were issues with `{{` being valid in python, but not jinja.  I imagined that the default should be that IPython works because less folks know jinja.  

You can enable the templates with `%reload_ext literacy.template`.  

Here's the catch though.  It is valuable for a notebook to be able to [restart and run all](https://cdn.rawgit.com/jupyterday-atlanta-2016/oriole_jupyterday_atl/d2ce13f2/oriole_talk.slides.html#What-we-learned-about-teaching-with-notebooks).  You must define an object in a cell before using it in a template. 

Here are some related examples

![screen shot 2017-09-26 at 1 05 40 pm](https://user-images.githubusercontent.com/4236275/30873497-773cf0be-a2bb-11e7-82d1-cd5f1bbde707.png)

**Comment by akvadrako** [comment]
Thanks! I was missing that reload line.
